export const FETCH_QUIZES_START = `FETCH_QUIZES_START`;
export const FETCH_QUIZES_SUCCESS = `FETCH_QUIZES_SUCCESS`;
export const FETCH_QUIZES_ERROR = `FETCH_QUIZES_ERROR`;
export const FETCH_QUIZ_SUCCESS = `FETCH_QUIZ_SUCCESS`;

export const QUIZ_NEXT_QUESTION = `QUIZ_NEXT_QUESTION`;
export const QUIZ_FINISH = `QUIZ_FINISH`;
export const SEND_QUIZ_ANSWER = `SEND_QUIZ_ANSWER`;
export const QUIZ_RESTART = `QUIZ_RESTART`;

export const ADD_QUESTION_ITEM_TO_LIST = `ADD_QUESTION_ITEM_TO_LIST`;
export const CLEAN_QUIZ_LIST = `CLEAN_QUIZ_LIST`;
